### ISSUE TITLE
SpringCloudCommandRouter requires local @CommandHandler to function properly

### ISSUE THREAD

**Issue by travikk** [AxonFramework/extension-springcloud#1]
Hey there!

I noticed that if a service wants to use DistributedCommandBus with SpringCloudCommandRouter it's not really possible to do so. SpringCloudCommandRouter will throw a 
`new IllegalStateException("There should be no scenario where the local member does not exist."`
 when there haven't been any local member (which would happen when subscribing for a local @CommandHandler?).

It is a perfectly valid scenario that a service would like to dispatch a method to another one, whilst it itself doesn't have any command handlers.

There's no obvious workaround currently, as things are declared as private, so can't really override stuff without copy-pasting the whole class.

Thanks for your help!

**Comment by travikk** [comment]
Thanks for replying!

Thanks for the suggestion on the workaround. Will try it, as currently I had setup a simple handler for a dummy command.

**Comment by smcvb** [comment]
Closing as this issue has been resolved in commit eefbbac.
