### ISSUE TITLE
Allow configuration of SpringCloudCommandRouter with a provided XStreamSerializer

### ISSUE THREAD

**Issue by martijnvanderwoud** [AxonFramework/extension-springcloud#13]
The serializer used by the `SpringCloudCommandRouter` is hard-coded. 

`protected final XStreamSerializer serializer = XStreamSerializer.builder().build();`

So far, I have not found a way to provide my own serializer. I would like to do so, since the hardcoded one produces this warning: "Security framework of XStream not initialized, XStream is probably vulnerable."

**Comment by smcvb** [comment]
Good point @martijnvanderwoud. It was hard coded to XStream as it is dedicated to serializing the `CommandFilter` which is shared with the other instances which will not go down to well with something like the `JacksonSerialzier`. At that point the warning didn't occur yet, hence why it's their.

Should be  easy enough to adjust this though. I would suggest to add a dedicated builder method in the `SpringCloudCommandRouter.Builder` which allows you to set the `XStreamSerializer`. That way, users have the ability to adjust the `XStreamSerializer` to a version which has an initialized XStream instance.

**Comment by martijnvanderwoud** [comment]
I agree Steven, would you like me to submit a PR for this? Might be a while before I find some time for this but is does not appear to be  very complicated

**Comment by smcvb** [comment]
If you would have the time to provide a PR @martijnvanderwoud, that would be great!

**Comment by martijnvanderwoud** [comment]
Thanks for fixing this @smcvb, sorry that I did not make time to create a PR (this was still on my todo list, but has been there for ages)
