### ISSUE TITLE
SimpleSpringCloudCommandRouter without Blacklisting and without CommandMessageFiltering

### ISSUE THREAD

**Issue by dhermanns** [AxonFramework/extension-springcloud#22]
Hi Axon Team!

If someone would like to use Consul right now you will have to use the SpringCloudHttpBackupCommandRouter. It introduces a special message endpoint.

This can add additional complexity and pitfalls e.g. if you have connection timeouts when calling this endpoint.

In our setup all Axon nodes are able to execute all existing commandmessages. So there is no need for this special feature. If you like I can contribute our so called SimpleSpringCloudRouter which doesn't care about commandmessage filtering.

This is why it's running fine on Consul without the need for a special backup messaging HTTP-Endpoint. The blacklisting feature is removed too since every Axon node discovered is able to handle all incoming Axon commands. This makes it for us more robust: Before this, aggregates needs to be "moved" from one node to the other just because of connection timeouts of the messaging endpoint.

**Comment by smcvb** [comment]
So, essentially you are looking for a feature which allows you to specify a given Axon node as residing in an entirely "homogeneous command handling environment", correct?

That would indeed eliminate the need to share a `CommandMessageFilter` other than `AcceptAll`.

I'd argue the black listing logic could still make sense, if one such node which accepts all is failing for other technical reasons. Added, when using Eureka for example a default EurekaServer instance would also be registered as a service, whilst this definitely isn't able to handle any commands, ever. Still having it blacklisted, keeping the assumption of an `AcceptAll` command filter would resolve perpetual exceptions.

Regardless, something like seems relevant to me. I've seen plenty scenarios where all Axon Nodes just handled every type of command. What do you think @abuijze, is this a good fit? Should we allow something like this on a higher level than just the Spring Cloud Extension even?

**Comment by dhermanns** [comment]
Regarding the EurekaServer: We are using Consul here. And with that setup, you have to filter every instance and there you could already filter out other nodes that you don't want to have for Command Handling. That is why it's fine for us at least in our scenario.

**Comment by smcvb** [comment]
Of course @dhermanns, that makes total sense.

FYI, the team has had a quick discussion around this issue and other related topics, which resulted in issue #23. We feel adding a Simple / AcceptAll command-discovery mechanism is indeed in place. I am pretty sure the flavor will be different than the actual implementation you have in place though; a code-contribution would thus not be necessary (yet).

**Comment by dhermanns** [comment]
Thanks - I will have a look at #23...

**Comment by smcvb** [comment]
I am pretty confident this issue can be resolved together with #23, hence I will be closing this for now. Feel free to keep commenting here if the need arrisses.

**Comment by dhermanns** [comment]
Yes - thx!

Steven van Beelen <notifications@github.com> schrieb am Di. 11. Aug. 2020
um 12:51:
