### ISSUE TITLE
Configurable Discovery Mode

### ISSUE THREAD

**Issue by smcvb** [AxonFramework/extension-springcloud#23]
As time has proven the original approach of the `SpringCloudCommandRouter`, thus using `ServiceInstance` metadata to communicate command handling capabilities, no longer suffices for a multitude of Spring Cloud Discovery mechanism implementations. This follows from the fact that as far as we know currently no implementation allows continued updates on this metadata in a live set up.

That leaves the `SpringCloudHttpBackupCommandRouter` as the sole reasonable solution, with a rather awkward naming attached to it. As it's no longer a back-up, but the _only_ solution.
We feel an overhaul on the `SpringCloudCommandRouter` is thus in place. 

Instead of the current set up we should introduce the capability to configure a (for a lack of better word) `DiscoveryMode` on the `SpringCloudCommandRouter`.

This `DiscoveryMode` would provide the implementation on how to receive and send command routing information from one instance to another. We think the following implementations would be reasonable to introduce:

- Dynamic-HTTP -> Essentially the current implementation of the `SpringCloudHttpBackupCommandRouter`. This should be the default.
- Simple / AcceptAll -> In a "homogeneous command handling"-system, each node can handle everything. Thus there is no real need to share this knowledge at all. Kuddos to @dhermanns in #22 for sharing this idea.

**Comment by dhermanns** [comment]
Sounds great! Thanks for picking that up!
