### ISSUE TITLE
Regarding Release 4.4

### ISSUE THREAD

**Issue by syd036** [AxonFramework/extension-springcloud#64]
Hi folks,

We are working on a new feature of our product which has a dependency on Release 4.4 of this artifact. Can you please advise its timeline if any, and then we can plan our development & release accordingly? 

Thanks.

**Comment by smcvb** [comment]
Hi @syd036, we aim not to provide any release dates to provide ourselves with some more freedom.
Regardless, 4.4 for this extension is somewhat overdue at this stage. Confident it would be released this year anymore, but close to the start of next year sounds reasonable to me.

On another note, questions like this are actually intended to be placed on our [forum](https://discuss.axoniq.io/). As such, I will be closing this issue right away. Trusting to have helped you out sufficiently.
